services:
  db_staging:
    image: postgres:15-alpine
    container_name: WaitIt-db-staging
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_staging:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - stagingNetwork

  server_staging:
    container_name: WaitIt-server-staging
    depends_on:
      db_staging:
        condition: service_healthy
    image: joffreychevalier/waitit-server:staging
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: 'db_staging'
      NODE_ENV: 'production'
    healthcheck:
      test: 'curl --fail --request GET -H ''content-type:application/json'' --url ''http://localhost:4000/graphql?query=%7B__typename%7D'''
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stagingNetwork

  client_staging:
    container_name: WaitIt-client-staging
    image: joffreychevalier/waitit-client:staging
    networks:
      - stagingNetwork

  nginx_staging:
    container_name: WaitIt-nginx-staging
    image: nginx:1.21.3
    depends_on:
      client_staging:
        condition: service_started
      server_staging:
        condition: service_healthy
    restart: always
    ports:
      - ${GATEWAY_PORT:-8001}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - stagingNetwork

volumes:
  db_staging:

networks:
  stagingNetwork:
