name: Build and push

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make server envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: "CECI_EST_UN_MOT_DE_PASSE"
          envkey_POSTGRES_USER: "CECI_EST_UN_UTILISATEUR"
          envkey_POSTGRES_DB: "CECI_EST_UNE_BASE_DE_DONNEES"
          envkey_POSTGRES_DB_TEST: "CECI_EST_UNE_BASE_DE_DONNEES_TEST"
          envkey_JWT_PRIVATE_KEY: "CECI_EST_UNE_CLE_PRIVEE"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          directory: ./server
          file_name: .env
          fail_on_empty: false

      - name: Make root envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: "CECI_EST_UN_MOT_DE_PASSE"
          envkey_POSTGRES_USER: "CECI_EST_UN_UTILISATEUR"
          envkey_POSTGRES_DB: "CECI_EST_UNE_BASE_DE_DONNEES"
          envkey_POSTGRES_DB_TEST: "CECI_EST_UNE_BASE_DE_DONNEES_TEST"
          directory: ./
          file_name: .env
          fail_on_empty: false


      - name: Build and run docker tests
        run: npm run test:docker

  build:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client_web"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/2209-wns-adleman-bordolamif:latest
          build-args: |
            "REACT_APP_GRAPHQL_API_URL=${{ vars.REACT_APP_GRAPHQL_API_URL }}"
