name: Build and push production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make root envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: "CECI_EST_UN_MOT_DE_PASSE"
          envkey_POSTGRES_USER: "CECI_EST_UN_UTILISATEUR"
          envkey_POSTGRES_DB: "CECI_EST_UNE_BASE_DE_DONNEES"
          envkey_POSTGRES_DB_TEST: "CECI_EST_UNE_BASE_DE_DONNEES_TEST"
          envkey_DB_PORT: 5432
          envkey_JWT_PRIVATE_KEY: "CECI_EST_UNE_CLE_PRIVEE"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: 4000
          envkey_EXPO_ACCESS_TOKEN: "CECI_EST_UN_TOKEN_EXPO"
          envkey_MJ_APIKEY_PUBLIC: "CECI_EST_UNE_CLE_MAILJET_PUBLIQUE"
          envkey_MJ_APIKEY_PRIVATE: "CECI_EST_UNE_CLE_MAILJET_PUBLIQUE"
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: Build and run docker tests
        run: npm run test:docker

  build-and-push-server:

    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: "Dockerfile.production"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/waitit-server

  build-and-push-client:

    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client_web"
          file: "Dockerfile.production"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/waitit-client

  notify:

    needs:
      - build-and-push-server
      - build-and-push-client

    runs-on: ubuntu-latest

    steps:
      - name: Call VPS webhook to update production
        uses: wei/curl@master
        with:
          args: https://ops.adleman5.wns.wilders.dev/hooks/update-production
