name: Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run docker tests
        run: npm run test:docker
