name: Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  create-envfile:
    name: Create envfile
    runs-on: ubuntu-latest

    steps:
      - name: Make server envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: "CECI_EST_UN_MOT_DE_PASSE"
          envkey_POSTGRES_USER: "CECI_EST_UN_UTILISATEUR"
          envkey_POSTGRES_DB: "CECI_EST_UNE_BASE_DE_DONNEES"
          envkey_POSTGRES_DB_TEST: "CECI_EST_UNE_BASE_DE_DONNEES_TEST"
          envkey_JWT_PRIVATE_KEY: "CECI_EST_UNE_CLE_PRIVEE"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          directory: ./server
          file_name: .env
          fail_on_empty: false

      - name: Make root envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: "CECI_EST_UN_MOT_DE_PASSE"
          envkey_POSTGRES_USER: "CECI_EST_UN_UTILISATEUR"
          envkey_POSTGRES_DB: "CECI_EST_UNE_BASE_DE_DONNEES"
          envkey_POSTGRES_DB_TEST: "CECI_EST_UNE_BASE_DE_DONNEES_TEST"
          directory: ./
          file_name: .env
          fail_on_empty: false

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run docker tests
        run: npm run test:docker
